services:
  db:
    ports:
      - 5432:5432
    container_name: psql
    image: postgres:alpine
    environment:
      - POSTGRES_DB=rentacar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
    volumes:
      - /Users/fatihsoymaz/postgres_data:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    image: fthsymz/application_img
    container_name: application_img
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://psql:5432/rentacar
      - DB_USERNAME=postgres
      - DB_PASSWORD=test
    depends_on:
      - db
    restart: always
  frontend:
    build: /Users/fatihsoymaz/Desktop/rentacarfrontend
    image: fthsymz/frontend_img
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: always